
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class ReviewTrainer extends javax.swing.JDialog {

    /**
     * Creates new form ReviewTrainer
     */
    public ReviewTrainer(java.awt.Frame parent, boolean modal, TrainingSession trainingsession) {
        super(parent, modal);
        initComponents();
        
        titleLabel.setText(trainingsession.getTitle());
        dateLabel.setText(trainingsession.getDate().toString());
        timeLabel.setText(trainingsession.getTime().toString());
        feeLabel.setText(String.format("%4.2f", trainingsession.getFee()));
        statLabel.setText(trainingsession.getStatus());
        
        if (trainingsession instanceof PersonalTraining) {
            typeTitleLabel.setVisible(false);
            typeLabel.setVisible(false);
            PersonalTraining personal = (PersonalTraining) trainingsession;
            if (personal.getNotes().isEmpty()) {
                NotesTitleLabel.setVisible(false);
                notesLabel.setVisible(false);
            }
            else
                notesLabel.setText(personal.getNotes());
            maxPartLabel.setVisible(false);
            MaxPartTitleLabel.setVisible(false);
            numPartLabel.setVisible(false);
            NumPartTitleLabel.setVisible(false);
            trainerLabel.setVisible(false);
            TrainerTitleLabel.setVisible(false);
            specialLabel.setVisible(false);
            SpecialTitleLabel.setVisible(false);
        }
        else {
            NotesTitleLabel.setVisible(false);
            notesLabel.setVisible(false);
            GroupTraining group = (GroupTraining) trainingsession;
            typeLabel.setText(group.getClassType());
            maxPartLabel.setText(Integer.toString(group.getMaxParticipants()));
            numPartLabel.setText(Integer.toString(group.getNumParticipants()));
            trainerLabel.setText(group.getUser().getUsername());
            specialLabel.setText(group.getUser().getSpecialty());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        submitBtn = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        statLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        feeLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        typeTitleLabel = new javax.swing.JLabel();
        notesLabel = new javax.swing.JLabel();
        NotesTitleLabel = new javax.swing.JLabel();
        maxPartLabel = new javax.swing.JLabel();
        MaxPartTitleLabel = new javax.swing.JLabel();
        numPartLabel = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        trainerLabel = new javax.swing.JLabel();
        TrainerTitleLabel = new javax.swing.JLabel();
        specialLabel = new javax.swing.JLabel();
        SpecialTitleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentTA = new javax.swing.JTextArea();
        NumPartTitleLabel = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        b1 = new javax.swing.JRadioButton();
        b6 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JRadioButton();
        b3 = new javax.swing.JRadioButton();
        b4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(25, 24, 28));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 0));
        jLabel13.setText("Date");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jPanel4.setBackground(new java.awt.Color(25, 24, 28));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(242, 146, 22)));

        submitBtn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        submitBtn.setText("Submit");
        submitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(submitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(submitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 830, 340, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Review");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(242, 146, 22));
        jSeparator6.setForeground(new java.awt.Color(242, 146, 22));
        jSeparator6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 340, 10));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 153, 0));
        jLabel17.setText("Title");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 153, 0));
        jLabel19.setText("Status");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("title");
        jPanel3.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("date");
        jPanel3.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        timeLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(255, 255, 255));
        timeLabel.setText("time");
        jPanel3.add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 153, 0));
        jLabel20.setText("Time");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        statLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        statLabel.setForeground(new java.awt.Color(255, 255, 255));
        statLabel.setText("status");
        jPanel3.add(statLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 153, 0));
        jLabel21.setText("Fee");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        feeLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        feeLabel.setForeground(new java.awt.Color(255, 255, 255));
        feeLabel.setText("fee");
        jPanel3.add(feeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        typeLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(255, 255, 255));
        typeLabel.setText("type");
        jPanel3.add(typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        typeTitleLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        typeTitleLabel.setForeground(new java.awt.Color(255, 153, 0));
        typeTitleLabel.setText("Type");
        jPanel3.add(typeTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        notesLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        notesLabel.setForeground(new java.awt.Color(255, 255, 255));
        notesLabel.setText("notes");
        jPanel3.add(notesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        NotesTitleLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        NotesTitleLabel.setForeground(new java.awt.Color(255, 153, 0));
        NotesTitleLabel.setText("Notes");
        jPanel3.add(NotesTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        maxPartLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        maxPartLabel.setForeground(new java.awt.Color(255, 255, 255));
        maxPartLabel.setText("max");
        jPanel3.add(maxPartLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        MaxPartTitleLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        MaxPartTitleLabel.setForeground(new java.awt.Color(255, 153, 0));
        MaxPartTitleLabel.setText("maxPartLabel");
        jPanel3.add(MaxPartTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        numPartLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        numPartLabel.setForeground(new java.awt.Color(255, 255, 255));
        numPartLabel.setText("number");
        jPanel3.add(numPartLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 153, 0));
        jLabel24.setText("Rating");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        trainerLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        trainerLabel.setForeground(new java.awt.Color(255, 255, 255));
        trainerLabel.setText("trainer");
        jPanel3.add(trainerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, -1, -1));

        TrainerTitleLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        TrainerTitleLabel.setForeground(new java.awt.Color(255, 153, 0));
        TrainerTitleLabel.setText("Trainer");
        jPanel3.add(TrainerTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, -1, -1));

        specialLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        specialLabel.setForeground(new java.awt.Color(255, 255, 255));
        specialLabel.setText("specialty");
        jPanel3.add(specialLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 750, -1, -1));

        SpecialTitleLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        SpecialTitleLabel.setForeground(new java.awt.Color(255, 153, 0));
        SpecialTitleLabel.setText("Specialty");
        jPanel3.add(SpecialTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 730, -1, -1));

        commentTA.setColumns(20);
        commentTA.setRows(5);
        jScrollPane1.setViewportView(commentTA);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 370, 200));

        NumPartTitleLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        NumPartTitleLabel.setForeground(new java.awt.Color(255, 153, 0));
        NumPartTitleLabel.setText("Number of Participants");
        jPanel3.add(NumPartTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1, -1));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 153, 0));
        jLabel28.setText("Comments");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        buttonGroup1.add(b1);
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("1");
        jPanel3.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        buttonGroup1.add(b6);
        b6.setForeground(new java.awt.Color(255, 255, 255));
        b6.setText("5");
        jPanel3.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, -1, -1));

        buttonGroup1.add(b2);
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setText("2");
        jPanel3.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        buttonGroup1.add(b3);
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setSelected(true);
        b3.setText("3");
        jPanel3.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        buttonGroup1.add(b4);
        b4.setForeground(new java.awt.Color(255, 255, 255));
        b4.setText("4");
        jPanel3.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseExited
        submitBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_submitBtnMouseExited

    private void submitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseEntered
        submitBtn.setForeground(new Color(242,146,22));
    }//GEN-LAST:event_submitBtnMouseEntered

    private void submitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseClicked
        if (b1.isSelected())
            setRatings(1);
        else if (b2.isSelected())
            setRatings(2);
        else if (b3.isSelected())
            setRatings(3);
        else if (b4.isSelected())
            setRatings(4);
        else
            setRatings(5);
        
        setComments(commentTA.getText());
        updated = true;
        this.setVisible(false);
    }//GEN-LAST:event_submitBtnMouseClicked

    public boolean isUpdated() {
        return updated;
    }
     
    private boolean updated = false;
    private int ratings;
    private String comments;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MaxPartTitleLabel;
    private javax.swing.JLabel NotesTitleLabel;
    private javax.swing.JLabel NumPartTitleLabel;
    private javax.swing.JLabel SpecialTitleLabel;
    private javax.swing.JLabel TrainerTitleLabel;
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JRadioButton b3;
    private javax.swing.JRadioButton b4;
    private javax.swing.JRadioButton b6;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea commentTA;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel feeLabel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel maxPartLabel;
    private javax.swing.JLabel notesLabel;
    private javax.swing.JLabel numPartLabel;
    private javax.swing.JLabel specialLabel;
    private javax.swing.JLabel statLabel;
    private javax.swing.JLabel submitBtn;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel trainerLabel;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel typeTitleLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the ratings
     */
    public int getRatings() {
        return ratings;
    }

    /**
     * @param ratings the ratings to set
     */
    public void setRatings(int ratings) {
        this.ratings = ratings;
    }

    /**
     * @return the comments
     */
    public String getComments() {
        return comments;
    }

    /**
     * @param comments the comments to set
     */
    public void setComments(String comments) {
        this.comments = comments;
    }
}
