
import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mint
 */
public class TrainerHome extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public TrainerHome(HELPFit helpfit, String username, Login login) {
        setHelpfit(helpfit);
        setUsername(username);
        setLogin(login);
        initComponents();
        header.setBackground(new Color(38,38,38,100));
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.WHITE);
        headerRenderer.setForeground(Color.BLACK);
        jScrollPane1.getViewport().setBackground(sessionTable.getBackground());
        jScrollPane3.getViewport().setBackground(sessionTable.getBackground());
        sessionTable.setColumnSelectionAllowed(false);
        contentHeader.setBackground(new Color(38,38,38,100));
        contentHeader.setVisible(false);
        profile.setVisible(false);
        newTraining.setVisible(false);
        usernameLabel.setText(getUser().getUsername());
        welcomemsg.setText("Hello, Trainer " + getUser().getName());
        history.setVisible(false);
        upcomingModel = new UpcomingTModel(getUser());
        sessionTable.setModel(upcomingModel);
        historyModel = new TrainerHistoryModel(getUser());
        historytb.setModel(historyModel);
        for (int i = 0; i < sessionTable.getModel().getColumnCount(); i++) {
                sessionTable.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        for (int i = 0; i < historytb.getModel().getColumnCount(); i++) {
                historytb.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nav = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        usernameLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        profileBtn = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        createBtn = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        viewBtn = new javax.swing.JLabel();
        contentHeader = new javax.swing.JPanel();
        headerTitle = new javax.swing.JLabel();
        headerDesc = new javax.swing.JLabel();
        history = new javax.swing.JPanel();
        historyBack = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        historytb = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        viewRevBtn = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        updateHistoryBtn = new javax.swing.JLabel();
        newTraining = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        createmsg = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        titleF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        nameF1 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        createSession = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        feeF = new javax.swing.JTextField();
        classtype = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        pSeperator = new javax.swing.JSeparator();
        gSeperator = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        date = new com.github.lgooddatepicker.components.DatePicker();
        time = new com.github.lgooddatepicker.components.TimePicker();
        maxPart = new javax.swing.JSpinner();
        profile = new javax.swing.JPanel();
        updatemsg = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        userF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        passF = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        emailF = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        LabelChanger = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nameF = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        updateBtn = new javax.swing.JLabel();
        cpassF = new javax.swing.JPasswordField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        specialtyBox = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        profileBack = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        welcomemsg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sessionTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setText("HELPFit");
        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));

        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("User100,");
        usernameLabel.setBackground(new java.awt.Color(255, 255, 255));
        usernameLabel.setFont(new java.awt.Font("Century Gothic", 0, 27)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(153, 153, 153));

        jPanel5.setBackground(new java.awt.Color(10, 10, 10));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profileBtn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        profileBtn.setForeground(new java.awt.Color(255, 255, 255));
        profileBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileBtn.setText("Edit Profile");
        profileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileBtnMouseExited(evt);
            }
        });
        jPanel5.add(profileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 280, 60));

        jPanel9.setBackground(new java.awt.Color(10, 10, 10));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutBtn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutBtn.setText("Logout");
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });
        jPanel9.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 280, 60));

        jPanel10.setBackground(new java.awt.Color(10, 10, 10));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createBtn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        createBtn.setForeground(new java.awt.Color(255, 255, 255));
        createBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createBtn.setText("Create Training Session");
        createBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createBtnMouseExited(evt);
            }
        });
        jPanel10.add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 280, 60));

        jPanel11.setBackground(new java.awt.Color(10, 10, 10));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewBtn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        viewBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewBtn.setText("View Training Session");
        viewBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewBtnMouseExited(evt);
            }
        });
        jPanel11.add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 280, 60));

        javax.swing.GroupLayout navLayout = new javax.swing.GroupLayout(nav);
        nav.setLayout(navLayout);
        navLayout.setHorizontalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(navLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(usernameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navLayout.setVerticalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(usernameLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        getContentPane().add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 630));

        contentHeader.setBackground(new java.awt.Color(38, 38, 38));

        headerTitle.setText("Trainer Profile");
        headerTitle.setFont(new java.awt.Font("Century Gothic", 0, 40)); // NOI18N
        headerTitle.setForeground(new java.awt.Color(255, 255, 255));

        headerDesc.setText("Account Settings");
        headerDesc.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        headerDesc.setForeground(new java.awt.Color(242, 146, 22));

        javax.swing.GroupLayout contentHeaderLayout = new javax.swing.GroupLayout(contentHeader);
        contentHeader.setLayout(contentHeaderLayout);
        contentHeaderLayout.setHorizontalGroup(
            contentHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentHeaderLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(contentHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentHeaderLayout.createSequentialGroup()
                        .addComponent(headerTitle)
                        .addGap(0, 422, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contentHeaderLayout.setVerticalGroup(
            contentHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentHeaderLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(headerTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerDesc)
                .addGap(14, 14, 14))
        );

        getContentPane().add(contentHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 770, 160));

        history.setBackground(new java.awt.Color(25, 24, 28));
        history.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        historyBack.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        historyBack.setForeground(new java.awt.Color(242, 146, 22));
        historyBack.setText("Back");
        historyBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historyBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyBackMouseClicked(evt);
            }
        });
        history.add(historyBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 60, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        jLabel6.setText("jLabel3");
        history.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 30, 30));

        historytb.setBackground(new java.awt.Color(240, 240, 240));
        historytb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        historytb.setGridColor(new java.awt.Color(102, 102, 102));
        historytb.setRowHeight(30);
        historytb.setSelectionBackground(new java.awt.Color(242, 146, 22));
        historytb.setSelectionForeground(new java.awt.Color(0, 0, 0));
        historytb.setShowHorizontalLines(false);
        historytb.setShowVerticalLines(false);
        jScrollPane3.setViewportView(historytb);

        history.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 700, 310));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(242, 146, 22)));

        viewRevBtn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        viewRevBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewRevBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewRevBtn.setText("View Review");
        viewRevBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewRevBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewRevBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewRevBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewRevBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewRevBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        history.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(242, 146, 22)));

        updateHistoryBtn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        updateHistoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateHistoryBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateHistoryBtn.setText("Update Session");
        updateHistoryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateHistoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateHistoryBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateHistoryBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateHistoryBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateHistoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateHistoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        history.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        getContentPane().add(history, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 770, 470));

        newTraining.setBackground(new java.awt.Color(25, 24, 28));
        newTraining.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(242, 146, 22));
        jLabel26.setText("Back");
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        newTraining.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 60, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        jLabel5.setText("jLabel3");
        newTraining.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 30, 30));

        createmsg.setBackground(new java.awt.Color(204, 0, 0));
        createmsg.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        createmsg.setForeground(new java.awt.Color(255, 51, 51));
        newTraining.add(createmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 700, 30));

        jSeparator12.setBackground(new java.awt.Color(242, 146, 22));
        jSeparator12.setForeground(new java.awt.Color(242, 146, 22));
        newTraining.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 340, 10));

        titleF.setBackground(new java.awt.Color(25, 24, 28));
        titleF.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        titleF.setForeground(new java.awt.Color(255, 255, 255));
        titleF.setText("Weightlifting Foundations");
        titleF.setBorder(null);
        newTraining.add(titleF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 343, 30));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(242, 146, 22));
        jLabel15.setText("DATE");
        newTraining.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(242, 146, 22));
        jLabel23.setText("MAXIMUM NUMBER OF PARTICIPANTS");
        newTraining.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 40));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(242, 146, 22));
        jLabel27.setText("CLASS TYPE");
        newTraining.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(242, 146, 22));
        jLabel24.setText("FEE");
        newTraining.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        nameF1.setBackground(new java.awt.Color(25, 24, 28));
        nameF1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        nameF1.setForeground(new java.awt.Color(255, 255, 255));
        nameF1.setText("RM");
        nameF1.setBorder(null);
        nameF1.setFocusable(false);
        newTraining.add(nameF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 30, 30));

        jSeparator15.setBackground(new java.awt.Color(242, 146, 22));
        jSeparator15.setForeground(new java.awt.Color(242, 146, 22));
        jSeparator15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newTraining.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 340, 10));

        jPanel6.setBackground(new java.awt.Color(25, 24, 28));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(242, 146, 22)));

        createSession.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        createSession.setForeground(new java.awt.Color(255, 255, 255));
        createSession.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createSession.setText("Create New Session");
        createSession.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createSessionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createSessionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createSessionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createSession, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createSession, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        newTraining.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 340, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(242, 146, 22));
        jLabel16.setText("TIME");
        newTraining.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(242, 146, 22));
        jLabel25.setText("TITLE");
        newTraining.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        feeF.setBackground(new java.awt.Color(25, 24, 28));
        feeF.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        feeF.setForeground(new java.awt.Color(255, 255, 255));
        feeF.setText("500.00");
        feeF.setBorder(null);
        newTraining.add(feeF, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 320, 30));

        classtype.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        classtype.setForeground(new java.awt.Color(255, 255, 255));
        classtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dance", "MMA", "Sport" }));
        newTraining.add(classtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 340, -1));

        jLabel18.setBackground(new java.awt.Color(242, 146, 22));
        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(242, 146, 22));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("PERSONAL");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        newTraining.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 350, 40));

        pSeperator.setBackground(new java.awt.Color(242, 146, 22));
        pSeperator.setForeground(new java.awt.Color(242, 146, 22));
        newTraining.add(pSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 350, 10));

        gSeperator.setBackground(new java.awt.Color(242, 146, 22));
        gSeperator.setForeground(new java.awt.Color(242, 146, 22));
        newTraining.add(gSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 350, 10));

        jLabel12.setBackground(new java.awt.Color(242, 146, 22));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(242, 146, 22));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("GROUP");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        newTraining.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 350, 40));

        date.setBackground(new java.awt.Color(25, 24, 28));
        date.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        newTraining.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 340, 30));

        time.setBackground(new java.awt.Color(25, 24, 28));
        time.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        newTraining.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 340, 30));

        maxPart.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        maxPart.setModel(new javax.swing.SpinnerNumberModel(5, 5, 50, 5));
        maxPart.setBorder(null);
        newTraining.add(maxPart, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 340, 30));

        getContentPane().add(newTraining, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 770, 470));

        profile.setBackground(new java.awt.Color(25, 24, 28));
        profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updatemsg.setBackground(new java.awt.Color(204, 0, 0));
        updatemsg.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        updatemsg.setForeground(new java.awt.Color(255, 51, 51));
        profile.add(updatemsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 700, 30));

        jSeparator8.setBackground(new java.awt.Color(242, 146, 22));
        jSeparator8.setForeground(new java.awt.Color(242, 146, 22));
        profile.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 340, 10));

        userF.setBackground(new java.awt.Color(25, 24, 28));
        userF.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        userF.setForeground(new java.awt.Color(255, 255, 255));
        userF.setText("Enter your username");
        userF.setBorder(null);
        profile.add(userF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 343, 30));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(242, 146, 22));
        jLabel13.setText("PASSWORD");
        profile.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        passF.setBackground(new java.awt.Color(25, 24, 28));
        passF.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        passF.setForeground(new java.awt.Color(255, 255, 255));
        passF.setText("jPasswordField1");
        passF.setBorder(null);
        profile.add(passF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 343, 30));

        jSeparator6.setBackground(new java.awt.Color(242, 146, 22));
        jSeparator6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator6.setForeground(new java.awt.Color(242, 146, 22));
        profile.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 340, 10));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(242, 146, 22));
        jLabel19.setText("EMAIL ADDRESS");
        profile.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        emailF.setBackground(new java.awt.Color(25, 24, 28));
        emailF.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        emailF.setForeground(new java.awt.Color(255, 255, 255));
        emailF.setText("jsmith@example.com");
        emailF.setBorder(null);
        profile.add(emailF, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 343, 30));

        jSeparator7.setBackground(new java.awt.Color(242, 146, 22));
        jSeparator7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator7.setForeground(new java.awt.Color(242, 146, 22));
        profile.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 340, 10));

        LabelChanger.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LabelChanger.setForeground(new java.awt.Color(242, 146, 22));
        LabelChanger.setText("LEVEL");
        profile.add(LabelChanger, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(242, 146, 22));
        jLabel21.setText("FULL NAME");
        profile.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        nameF.setBackground(new java.awt.Color(25, 24, 28));
        nameF.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        nameF.setForeground(new java.awt.Color(255, 255, 255));
        nameF.setText("John Smith");
        nameF.setBorder(null);
        profile.add(nameF, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 343, 30));

        jSeparator10.setBackground(new java.awt.Color(242, 146, 22));
        jSeparator10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator10.setForeground(new java.awt.Color(242, 146, 22));
        profile.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 340, 10));

        jPanel4.setBackground(new java.awt.Color(25, 24, 28));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(242, 146, 22)));

        updateBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateBtn.setText("Update Changes");
        updateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        profile.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 340, -1));

        cpassF.setBackground(new java.awt.Color(25, 24, 28));
        cpassF.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cpassF.setForeground(new java.awt.Color(255, 255, 255));
        cpassF.setText("jPasswordField1");
        cpassF.setBorder(null);
        profile.add(cpassF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 343, 30));

        jSeparator9.setBackground(new java.awt.Color(242, 146, 22));
        jSeparator9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator9.setForeground(new java.awt.Color(242, 146, 22));
        profile.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 340, 10));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(242, 146, 22));
        jLabel14.setText("RE-ENTER PASSWORD");
        profile.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        specialtyBox.setBackground(new java.awt.Color(25, 24, 28));
        specialtyBox.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        specialtyBox.setForeground(new java.awt.Color(255, 255, 255));
        specialtyBox.setText("Taekwondo, Yoga...");
        specialtyBox.setBorder(null);
        profile.add(specialtyBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 343, 30));

        jSeparator11.setBackground(new java.awt.Color(242, 146, 22));
        jSeparator11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator11.setForeground(new java.awt.Color(242, 146, 22));
        profile.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 340, 10));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(242, 146, 22));
        jLabel22.setText("USERNAME");
        profile.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        profileBack.setText("Back");
        profileBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileBack.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        profileBack.setForeground(new java.awt.Color(242, 146, 22));
        profileBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBackMouseClicked(evt);
            }
        });
        profile.add(profileBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 60, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        profile.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 30, 30));

        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 770, 470));

        header.setBackground(new java.awt.Color(38, 38, 38));
        header.setForeground(new java.awt.Color(255, 255, 255));

        welcomemsg.setText("Hello, Trainer Name!");
        welcomemsg.setFont(new java.awt.Font("Century Gothic", 0, 40)); // NOI18N
        welcomemsg.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Welcome back.");
        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(welcomemsg))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(welcomemsg)
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 760, 240));

        body.setBackground(new java.awt.Color(25, 24, 28));

        jScrollPane1.setBorder(null);

        sessionTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sessionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sessionTable.setBackground(new java.awt.Color(240, 240, 240));
        sessionTable.setGridColor(new java.awt.Color(102, 102, 102));
        sessionTable.setRowHeight(30);
        sessionTable.setSelectionBackground(new java.awt.Color(242, 146, 22));
        sessionTable.setShowHorizontalLines(false);
        sessionTable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(sessionTable);

        jLabel17.setText("Upcoming Training Sessions");
        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 33)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(242, 146, 22));

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel17)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 240, 764, 390));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_4.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 840, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseEntered
        updateBtn.setForeground(new Color(242,146,22));
    }//GEN-LAST:event_updateBtnMouseEntered

    private void updateBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseExited
        updateBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_updateBtnMouseExited

    private void profileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseClicked
        userF.setText(getUser().getUsername());
        userF.setFocusable(false);
        nameF.setText(getUser().getName());
        passF.setText(getUser().getPassword());
        cpassF.setText("");
        emailF.setText(getUser().getEmail());
        specialtyBox.setText(getUser().getSpecialty());
        headerTitle.setText("Trainer Profile");
        headerDesc.setText("Account Settings");
        profile.setVisible(true);
        contentHeader.setVisible(true);
        body.setVisible(false);
        header.setVisible(false);
        newTraining.setVisible(false);
        history.setVisible(false);
        updatemsg.setText("");
    }//GEN-LAST:event_profileBtnMouseClicked

    private void profileBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseEntered
        jPanel5.setBackground(new Color(242,146,22));
        profileBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_profileBtnMouseEntered

    private void profileBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseExited
        jPanel5.setBackground(new Color(10,10,10));
        profileBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_profileBtnMouseExited

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        jPanel9.setBackground(new Color(242,146,22));
        logoutBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
        jPanel9.setBackground(new Color(10,10,10));
        logoutBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_logoutBtnMouseExited

    private void createBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createBtnMouseEntered
        jPanel10.setBackground(new Color(242,146,22));
        createBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_createBtnMouseEntered

    private void createBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createBtnMouseExited
        jPanel10.setBackground(new Color(10,10,10));
        createBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_createBtnMouseExited

    private void viewBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBtnMouseEntered
        jPanel11.setBackground(new Color(242,146,22));
        viewBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_viewBtnMouseEntered

    private void viewBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBtnMouseExited
        jPanel11.setBackground(new Color(10,10,10));
        viewBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_viewBtnMouseExited

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        if (!cpassF.getText().equals(passF.getText())){
            updatemsg.setForeground(new Color(255,51,51));
            updatemsg.setText("Password does not match.");
            return;
        }
        
        getUser().setName(nameF.getText());
        getUser().setEmail(emailF.getText());
        getUser().setPassword(passF.getText());
        getUser().setSpecialty(specialtyBox.getText());
        updatemsg.setForeground(Color.green);
        updatemsg.setText("Update successfully.");
        welcomemsg.setText("Hello, Trainer " + getUser().getName());
    }//GEN-LAST:event_updateBtnMouseClicked

    private void profileBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBackMouseClicked
        profile.setVisible(false);
        contentHeader.setVisible(false);
        body.setVisible(true);
        header.setVisible(true);
        newTraining.setVisible(false);
        updatemsg.setText("");
    }//GEN-LAST:event_profileBackMouseClicked

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        profile.setVisible(false);
        contentHeader.setVisible(false);
        newTraining.setVisible(false);
        body.setVisible(true);
        header.setVisible(true);
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void createBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createBtnMouseClicked
        newTraining.setVisible(true);
        contentHeader.setVisible(true);
        body.setVisible(false);
        header.setVisible(false);
        profile.setVisible(false);
        createmsg.setText("");
        pSeperator.setVisible(true);
        gSeperator.setVisible(false);
        jLabel23.setVisible(false);
        jLabel27.setVisible(false);
        classtype.setVisible(false);
        history.setVisible(false);
        headerTitle.setText("Create New Training Session");
        headerDesc.setText("");
        maxPart.setVisible(false);
    }//GEN-LAST:event_createBtnMouseClicked

    private void historyBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyBackMouseClicked
        contentHeader.setVisible(false);
        body.setVisible(true);
        header.setVisible(true);
        history.setVisible(false);
    }//GEN-LAST:event_historyBackMouseClicked

    private void viewRevBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRevBtnMouseEntered
        viewRevBtn.setForeground(new Color(242,146,22));
    }//GEN-LAST:event_viewRevBtnMouseEntered

    private void viewRevBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRevBtnMouseExited
        viewRevBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_viewRevBtnMouseExited

    private void updateHistoryBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateHistoryBtnMouseEntered
        updateHistoryBtn.setForeground(new Color(242,146,22));
    }//GEN-LAST:event_updateHistoryBtnMouseEntered

    private void updateHistoryBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateHistoryBtnMouseExited
        updateHistoryBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_updateHistoryBtnMouseExited

    private void viewBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBtnMouseClicked
        history.setVisible(true);
        contentHeader.setVisible(true);
        body.setVisible(false);
        header.setVisible(false);
        profile.setVisible(false);
        newTraining.setVisible(false);
        headerTitle.setText("View Training Sessions");
        headerDesc.setText("");
    }//GEN-LAST:event_viewBtnMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        gSeperator.setVisible(true);
        pSeperator.setVisible(false);
        gSeperator.setVisible(true);
        jLabel23.setVisible(true);
        jLabel27.setVisible(true);
        classtype.setVisible(true);
        maxPart.setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        gSeperator.setVisible(false);
        pSeperator.setVisible(true);
        gSeperator.setVisible(false);
        jLabel23.setVisible(false);
        jLabel27.setVisible(false);
        classtype.setVisible(false);
        maxPart.setVisible(false);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void createSessionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createSessionMouseExited
        createSession.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_createSessionMouseExited

    private void createSessionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createSessionMouseEntered
        createSession.setForeground(new Color(242,146,22));
    }//GEN-LAST:event_createSessionMouseEntered

    private void createSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createSessionMouseClicked
        double fee;
        
        try {
        fee = Double.parseDouble(feeF.getText());
        }
        catch(NumberFormatException nfe){
            createmsg.setForeground(Color.red);
            createmsg.setText("Please enter correct amount of fee.");
            return;
        }
        
            if (pSeperator.isVisible()){
                getUser().getTrainingsession().add(new PersonalTraining(titleF.getText(),
                date.getDate(),time.getTime(),fee,"Available", ""));
                getHelpfit().getSession().add(new PersonalTraining(titleF.getText(),
                date.getDate(),time.getTime(),fee,"Available", ""));
            }
            else{
                getUser().getTrainingsession().add(new GroupTraining(titleF.getText(),
                        date.getDate(),time.getTime(),fee,"Available",
                        classtype.getSelectedItem().toString(),(int)maxPart.getValue()));
                getHelpfit().getSession().add(new GroupTraining(titleF.getText(),
                        date.getDate(),time.getTime(),fee,"Available",
                        classtype.getSelectedItem().toString(),(int)maxPart.getValue()));
            }

        createmsg.setForeground(Color.green);
        createmsg.setText("Successfully added new training session.");
        upcomingModel.fireTableDataChanged();
        historyModel.fireTableDataChanged();
    }//GEN-LAST:event_createSessionMouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        newTraining.setVisible(false);
        contentHeader.setVisible(false);
        body.setVisible(true);
        header.setVisible(true);
        profile.setVisible(false);
        createmsg.setText("");
    }//GEN-LAST:event_jLabel26MouseClicked

    private void updateHistoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateHistoryBtnMouseClicked
        UpdateTrainingRecord update = new UpdateTrainingRecord(this, true, getUser().getTrainingsession().get(historytb.getSelectedRow()));
        update.setVisible(true);
        if (update.isUpdated()){
            if (getUser().getTrainingsession().get(historytb.getSelectedRow()) instanceof PersonalTraining) {
                PersonalTraining personal = (PersonalTraining) getUser().getTrainingsession().get(historytb.getSelectedRow());
                personal.setDate(update.getDates());
                personal.setFee(update.getFee());
                personal.setStatus(update.getStatus());
                personal.setTime(update.getTimes());
                personal.setNotes(update.getNotes());
            }
            else {
                GroupTraining group = (GroupTraining) getUser().getTrainingsession().get(historytb.getSelectedRow());
                group.setDate(update.getDates());
                group.setFee(update.getFee());
                group.setStatus(update.getStatus());
                group.setTime(update.getTimes());
                group.setClassType(update.getClassType());
            }
            historyModel.fireTableDataChanged();
            upcomingModel.fireTableDataChanged();
        }
    }//GEN-LAST:event_updateHistoryBtnMouseClicked

    private HELPFit helpfit;
    private String username;
    private Login login;
    private UpcomingTModel upcomingModel;
    private TrainerHistoryModel historyModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelChanger;
    private javax.swing.JPanel body;
    private javax.swing.JComboBox<String> classtype;
    private javax.swing.JPanel contentHeader;
    private javax.swing.JPasswordField cpassF;
    private javax.swing.JLabel createBtn;
    private javax.swing.JLabel createSession;
    private javax.swing.JLabel createmsg;
    private com.github.lgooddatepicker.components.DatePicker date;
    private javax.swing.JTextField emailF;
    private javax.swing.JTextField feeF;
    private javax.swing.JSeparator gSeperator;
    private javax.swing.JPanel header;
    private javax.swing.JLabel headerDesc;
    private javax.swing.JLabel headerTitle;
    private javax.swing.JPanel history;
    private javax.swing.JLabel historyBack;
    private javax.swing.JTable historytb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JSpinner maxPart;
    private javax.swing.JTextField nameF;
    private javax.swing.JTextField nameF1;
    private javax.swing.JPanel nav;
    private javax.swing.JPanel newTraining;
    private javax.swing.JSeparator pSeperator;
    private javax.swing.JPasswordField passF;
    private javax.swing.JPanel profile;
    private javax.swing.JLabel profileBack;
    private javax.swing.JLabel profileBtn;
    private javax.swing.JTable sessionTable;
    private javax.swing.JTextField specialtyBox;
    private com.github.lgooddatepicker.components.TimePicker time;
    private javax.swing.JTextField titleF;
    private javax.swing.JLabel updateBtn;
    private javax.swing.JLabel updateHistoryBtn;
    private javax.swing.JLabel updatemsg;
    private javax.swing.JTextField userF;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel viewBtn;
    private javax.swing.JLabel viewRevBtn;
    private javax.swing.JLabel welcomemsg;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the helpfit
     */
    public HELPFit getHelpfit() {
        return helpfit;
    }

    /**
     * @param Helpfit the Helpfit to set
     */
    public void setHelpfit(HELPFit Helpfit) {
        this.helpfit = Helpfit;
    }

    /**
     * @return the user
     */
    public Trainer getUser() {
        for (User aUser: helpfit.getUser()){
            if (aUser.getUsername().equalsIgnoreCase(username)){
                return (Trainer)aUser;
            }
        }
        return null;
    }

    /**
     * @param username the username to set
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * @param login the login to set
     */
    public void setLogin(Login login) {
        this.login = login;
    }
}