
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class UpdateTrainingRecord extends javax.swing.JDialog {

    /**
     * Creates new form UpdateTrainingRecord
     */
    public UpdateTrainingRecord(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        updateBtn = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TypeTitleLabel = new javax.swing.JLabel();
        maxPartLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        numPartLabel = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        NotesTitleLabel = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        typeTF = new javax.swing.JTextField();
        dateTF = new javax.swing.JTextField();
        timeTF = new javax.swing.JTextField();
        feeTF = new javax.swing.JTextField();
        statTF = new javax.swing.JTextField();
        notesTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(25, 24, 28));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Date");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jPanel4.setBackground(new java.awt.Color(25, 24, 28));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(242, 146, 22)));

        updateBtn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateBtn.setText("Update");
        updateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 780, 340, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Update Training Record");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("Title");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("Status");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("title");
        jPanel3.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("Time");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("Fee");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        TypeTitleLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        TypeTitleLabel.setForeground(new java.awt.Color(153, 153, 153));
        TypeTitleLabel.setText("Type");
        jPanel3.add(TypeTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        maxPartLabel.setForeground(new java.awt.Color(255, 255, 255));
        maxPartLabel.setText("max");
        jPanel3.add(maxPartLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, -1, -1));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("Max. Participants");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, -1, -1));

        numPartLabel.setForeground(new java.awt.Color(255, 255, 255));
        numPartLabel.setText("number");
        jPanel3.add(numPartLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 710, -1, -1));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 153, 153));
        jLabel27.setText("Number of Participants");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, -1, -1));

        NotesTitleLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        NotesTitleLabel.setForeground(new java.awt.Color(153, 153, 153));
        NotesTitleLabel.setText("Notes");
        jPanel3.add(NotesTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(242, 146, 22));
        jSeparator7.setForeground(new java.awt.Color(242, 146, 22));
        jSeparator7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 340, 10));

        typeTF.setText("type");
        typeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeTFActionPerformed(evt);
            }
        });
        jPanel3.add(typeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 320, -1));

        dateTF.setText("date");
        dateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTFActionPerformed(evt);
            }
        });
        jPanel3.add(dateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 320, -1));

        timeTF.setText("time");
        timeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTFActionPerformed(evt);
            }
        });
        jPanel3.add(timeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 320, -1));

        feeTF.setText("fee");
        feeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeTFActionPerformed(evt);
            }
        });
        jPanel3.add(feeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 320, -1));

        statTF.setText("stat");
        statTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statTFActionPerformed(evt);
            }
        });
        jPanel3.add(statTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 320, -1));

        notesTF.setText("notes");
        notesTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesTFActionPerformed(evt);
            }
        });
        jPanel3.add(notesTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 320, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeTFActionPerformed

    private void updateBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseExited
        updateBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_updateBtnMouseExited

    private void updateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseEntered
        updateBtn.setForeground(new Color(242,146,22));
    }//GEN-LAST:event_updateBtnMouseEntered

    private void dateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTFActionPerformed

    private void timeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeTFActionPerformed

    private void feeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feeTFActionPerformed

    private void statTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statTFActionPerformed

    private void notesTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notesTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notesTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateTrainingRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateTrainingRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateTrainingRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateTrainingRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateTrainingRecord dialog = new UpdateTrainingRecord(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NotesTitleLabel;
    private javax.swing.JLabel TypeTitleLabel;
    private javax.swing.JTextField dateTF;
    private javax.swing.JTextField feeTF;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel maxPartLabel;
    private javax.swing.JTextField notesTF;
    private javax.swing.JLabel numPartLabel;
    private javax.swing.JTextField statTF;
    private javax.swing.JTextField timeTF;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField typeTF;
    private javax.swing.JLabel updateBtn;
    // End of variables declaration//GEN-END:variables
}
