
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class UpdateTrainingRecord extends javax.swing.JDialog {

    /**
     * Creates new form UpdateTrainingRecord
     */
    public UpdateTrainingRecord(java.awt.Frame parent, boolean modal, TrainingSession trainingsession) {
        super(parent, modal);
        initComponents();
        
        titleLabel.setText(trainingsession.getTitle());
        date.setDate(trainingsession.getDate());
        time.setTime(trainingsession.getTime());
        feeTF.setText(String.format("%4.2f", trainingsession.getFee()));
        statBox.setSelectedItem(trainingsession.getStatus());
        
        if (trainingsession instanceof PersonalTraining) {
            TypeTitleLabel.setVisible(false);
            typeBox.setVisible(false);
            PersonalTraining personal = (PersonalTraining) trainingsession;
            notesTF.setText(personal.getNotes());
            maxPartLabel.setVisible(false);
            maxPartTitleLabel.setVisible(false);
            numPartLabel.setVisible(false);
            numPartTitleLabel.setVisible(false);
        }
        else {
            NotesTitleLabel.setVisible(false);
            notesTF.setVisible(false);
            notesLine.setVisible(false);
            GroupTraining group = (GroupTraining) trainingsession;
            typeBox.setSelectedItem(group.getClassType());
            maxPartLabel.setText(Integer.toString(group.getMaxParticipants()));
            numPartLabel.setText(Integer.toString(group.getNumParticipants()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        updateBtn = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TypeTitleLabel = new javax.swing.JLabel();
        maxPartLabel = new javax.swing.JLabel();
        maxPartTitleLabel = new javax.swing.JLabel();
        numPartLabel = new javax.swing.JLabel();
        numPartTitleLabel = new javax.swing.JLabel();
        NotesTitleLabel = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        statBox = new javax.swing.JComboBox<>();
        date = new com.github.lgooddatepicker.components.DatePicker();
        time = new com.github.lgooddatepicker.components.TimePicker();
        nameF1 = new javax.swing.JTextField();
        notesLine = new javax.swing.JSeparator();
        notesTF = new javax.swing.JTextField();
        feeTF = new javax.swing.JTextField();
        feeF2 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        typeBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(25, 24, 28));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 0));
        jLabel13.setText("Date");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jPanel4.setBackground(new java.awt.Color(25, 24, 28));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(242, 146, 22)));

        updateBtn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateBtn.setText("Update");
        updateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 780, 340, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Update Training Record");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 153, 0));
        jLabel17.setText("Title");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 153, 0));
        jLabel19.setText("Status");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("title");
        jPanel3.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 153, 0));
        jLabel20.setText("Time");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 153, 0));
        jLabel21.setText("Fee");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        TypeTitleLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        TypeTitleLabel.setForeground(new java.awt.Color(255, 153, 0));
        TypeTitleLabel.setText("Type");
        jPanel3.add(TypeTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        maxPartLabel.setText("max");
        maxPartLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        maxPartLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(maxPartLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, -1, -1));

        maxPartTitleLabel.setText("Max. Participants");
        maxPartTitleLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        maxPartTitleLabel.setForeground(new java.awt.Color(255, 153, 0));
        jPanel3.add(maxPartTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, -1));

        numPartLabel.setText("number");
        numPartLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        numPartLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(numPartLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 710, -1, -1));

        numPartTitleLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        numPartTitleLabel.setForeground(new java.awt.Color(255, 153, 0));
        numPartTitleLabel.setText("Number of Participants");
        jPanel3.add(numPartTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, -1, -1));

        NotesTitleLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        NotesTitleLabel.setForeground(new java.awt.Color(255, 153, 0));
        NotesTitleLabel.setText("Notes");
        jPanel3.add(NotesTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(242, 146, 22));
        jSeparator7.setForeground(new java.awt.Color(242, 146, 22));
        jSeparator7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 340, 10));

        statBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cancelled", "Full", "Completed", "Available" }));
        statBox.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        statBox.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(statBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 320, -1));

        date.setBackground(new java.awt.Color(25, 24, 28));
        date.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel3.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 320, 30));

        time.setBackground(new java.awt.Color(25, 24, 28));
        time.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel3.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 320, 30));

        nameF1.setText("RM");
        nameF1.setBackground(new java.awt.Color(25, 24, 28));
        nameF1.setBorder(null);
        nameF1.setFocusable(false);
        nameF1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        nameF1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(nameF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 30, 30));

        notesLine.setBackground(new java.awt.Color(242, 146, 22));
        notesLine.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        notesLine.setForeground(new java.awt.Color(242, 146, 22));
        jPanel3.add(notesLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 320, 10));

        notesTF.setText("notes");
        notesTF.setBackground(new java.awt.Color(25, 24, 28));
        notesTF.setBorder(null);
        notesTF.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        notesTF.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(notesTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 290, 30));

        feeTF.setText("500.00");
        feeTF.setBackground(new java.awt.Color(25, 24, 28));
        feeTF.setBorder(null);
        feeTF.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        feeTF.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(feeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 290, 30));

        feeF2.setBackground(new java.awt.Color(25, 24, 28));
        feeF2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        feeF2.setForeground(new java.awt.Color(255, 255, 255));
        feeF2.setText("500.00");
        feeF2.setBorder(null);
        jPanel3.add(feeF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 290, 30));

        jSeparator16.setBackground(new java.awt.Color(242, 146, 22));
        jSeparator16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator16.setForeground(new java.awt.Color(242, 146, 22));
        jPanel3.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 320, 10));

        typeBox.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        typeBox.setForeground(new java.awt.Color(255, 255, 255));
        typeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dance", "MMA", "Sport" }));
        jPanel3.add(typeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 320, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseExited
        updateBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_updateBtnMouseExited

    private void updateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseEntered
        updateBtn.setForeground(new Color(242,146,22));
    }//GEN-LAST:event_updateBtnMouseEntered

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        dates = date.getDate();
        times = time.getTime();
        
        try {
        fee = Double.parseDouble(feeTF.getText());
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Please enter appropriate amount of fee.");
            return;
        }
        
        status = statBox.getSelectedItem().toString();
        classType = typeBox.getSelectedItem().toString();
        notes = notesTF.getText();
        updated = true;
        this.setVisible(false);
    }//GEN-LAST:event_updateBtnMouseClicked
    
    private boolean updated = false;
    private String classType;
    private String notes;
    private LocalDate dates;
    private LocalTime times;
    private double fee;
    private String status;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NotesTitleLabel;
    private javax.swing.JLabel TypeTitleLabel;
    private com.github.lgooddatepicker.components.DatePicker date;
    private javax.swing.JTextField feeF2;
    private javax.swing.JTextField feeTF;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel maxPartLabel;
    private javax.swing.JLabel maxPartTitleLabel;
    private javax.swing.JTextField nameF1;
    private javax.swing.JSeparator notesLine;
    private javax.swing.JTextField notesTF;
    private javax.swing.JLabel numPartLabel;
    private javax.swing.JLabel numPartTitleLabel;
    private javax.swing.JComboBox<String> statBox;
    private com.github.lgooddatepicker.components.TimePicker time;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JComboBox<String> typeBox;
    private javax.swing.JLabel updateBtn;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the classType
     */
    public String getClassType() {
        return classType;
    }

    /**
     * @return the notes
     */
    public String getNotes() {
        return notes;
    }

    /**
     * @return the dates
     */
    public LocalDate getDates() {
        return dates;
    }

    /**
     * @return the times
     */
    public LocalTime getTimes() {
        return times;
    }

    /**
     * @return the fee
     */
    public double getFee() {
        return fee;
    }

    /**
     * @return the status
     */
    public String getStatus() {
        return status;
    }

    /**
     * @return the updated
     */
    public boolean isUpdated() {
        return updated;
    }
}
